version: '3.1'

services:

  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_DB: my_task
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - '5102:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
